trigger:
  batch: true
  branches:
    include:
      - main

pr:
  - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy
  - name: environment_components
    type: object
    default:
      - deployment: 'sbox_project'
        environment: 'sbox'
        component: 'project-layer'
        service_connection: 'DTS-DATAINGEST-SBOX'
        dependsOn: 'Precheck'
      - deployment: 'stg_project'
        environment: 'stg'
        component: 'project-layer'
        service_connection: 'DTS-DATAINGEST-STG'
        dependsOn: 'sbox_project'
      - deployment: 'prod_project'
        environment: 'prod'
        component: 'project-layer'
        service_connection: 'DTS-DATAINGEST-PROD'
        dependsOn: 'stg_project'

variables:
  - name: timeoutInMinutes
    value: 240
  - name: agentImage
    value: ubuntu-latest
  - name: product
    value: dlrm-ingest
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

stages:
  - stage: Precheck
    jobs:
      - job:
        pool: 
          vmImage: ${{ variables.agentImage }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-sp-token'
              serviceConnection: 'azurerm-sandbox'
              overrideAction: ${{ parameters.overrideAction }}

  - ${{ each deployment in parameters.environment_components }}:
    - stage: ${{ deployment.deployment }}
      dependsOn: ${{ deployment.dependsOn }}
      jobs:
        - job: TerraformPlanApply
          ${{ if eq(deployment.environment, 'sbox') }}:
            pool: hmcts-sds-ptlsbox
          ${{ else }}:
            pool: hmcts-sds-ptl
          timeoutInMinutes: ${{ variables.timeoutInMinutes }}
          steps:
            - template: steps/terraform.yaml@cnp-azuredevops-libraries
              parameters:
                overrideAction: ${{ parameters.overrideAction }}
                environment: ${{ deployment.environment }}
                component: ${{ deployment.component }}
                serviceConnection: ${{ deployment.service_connection }}
                terraformInitSubscription: ${{ variables.terraformInitSubscription }}
                product: ${{ variables.product }}
                planCommandOptions: '-compact-warnings'